[project]
name = "loader"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.2.2",
    "fastapi[standard]>=0.115.12",
    "hdfs>=2.7.3",
    "requests>=2.32.3",
    "uvicorn[standard]>=0.34.2",
]
